name: Commit date to main

on: 
    push:
      branches: [ main ]
    workflow_dispatch:

jobs:
  date:
    runs-on: ubuntu-latest
      
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.
        with:
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: setup git config
        env:
          TOKEN_GIT: ${{ secrets.TOKEN_GITHUB }}
        run: |
          CLONE_DIR=$(mktemp -d)
          git config user.name "alexgarzar"
          git config user.email "alejandro.garza@nxp.com"
          git clone --single-branch --branch main "https://x-access-token:"$TOKEN_GIT"@github.com/alexgarzar/files.git" "$CLONE_DIR"
          git fetch --unshallow origin
          ls -la "$CLONE_DIR"
          
          TARGET_DIR=$(mktemp -d)
          mv "$CLONE_DIR/.git" "$TARGET_DIR"
          date > time.txt
          cp time.txt "$TARGET_DIR"
          cd "$TARGET_DIR"
          ls -la
      - name: commit
        run: |
          # Stage the file, commit and push
          git add time.txt
          git status
          git diff-index --quiet HEAD || git commit -m "new date commit"
          git push "https://alexgarzar:"$TOKEN_GIT"@github.com/alexgarzar/files.git" --set-upstream main --force
